config/routes.rb
	Rails.application.routes.draw do
  get 'welcome/index'

  resources :users, only: [:show, :destroy]
  resources :repositories, except: [:edit] do
    resources :notes
  end


  root "welcome#index"

  get '/test', :to => 'repositories#test'

  get '/search', :to => 'searches#index'

  get '/code-review', :to => 'code_reviews#new_code_review'

  get '/branch', :to => 'repositories#change_branch'

  # Github Callback
  get '/auth/github/callback', to: 'sessions#create'
  # Logout
  get '/sessions/destroy', to: 'sessions#destroy', as: :logout

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :repositories
	has_many :repository_files, through: :repositories
	has_many :notes

	def self.create_with_omniauth(auth)
		create do |user|
			user.github_uid = 			auth["uid"]
			user.name = 						auth["info"]["name"]
			user.email = 						auth["info"]["email"]
			user.github_username = 	auth["info"]["nickname"]
			user.avatar_url = 			auth["info"]["image"]
		end
	end

	def find_by_github_uid(github_uid)
		User.find_by(github_uid: github_uid)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper

  def show
    @user = User.find(session[:user_id])
    @repositories = @user.repositories
  end

	private

	def user_params
		params.require(:user).permit(:avatar_url, :email, :name)
	end
end

app/views/users/_dashboard.html.erb
<section class="container-fluid inner_container">
	<section class="row my_code_review_row">
		<section class="col-md-5 col-sm-6 col-xs-12">
			<h3 id="my_code_reviews_header" class="page_titles">
				My Repositories
				<i class="fa fa-code code_icon"></i>
			</h3>
		</section>
		<section class="col-md-5 col-sm-3 col-xs-0"></section>
		<section class="col-md-2 col-sm-3 col-xs-0"></section>
	</section>
<% unless @repositories.nil? %>
	<% @repositories.each do |repository| %>
		<%= render partial: 'users/dashboard_rows', locals: {repository: repository} %>
	<% end %>
<% end %>
</section>

app/views/users/_dashboard_rows.html.erb
<section class="my_repo_row row">
	<section class="col-md-3 col-sm-4 col-xs-5 repo_name">
		<i class="fa fa-folder-open"></i>
		<%= link_to "#{repository.name}", repository_path(repository) %>
	</section>
	<section class="col-md-7 col-sm-4 col-xs-3 repo_owner_name">
		<i class="fa fa-user"></i>
		<%= repository['repo_owner'] %>
	</section>
	<section class="col-md-2 col-sm-4 col-xs-4">
		<%= button_to "Delete", repository_path(repository), method: :delete, class: "delete-from-dashboard" %>
		<span class="date"><%= last_checked(repository).strftime("%b %d") %></span>
		<i class="fa fa-clock-o"></i>
	</section>
</section>

app/views/users/show.html.erb
<%= render partial: 'dashboard' %>