config/routes.rb
	Rails.application.routes.draw do
  get 'welcome/index'

  resources :users, only: [:show, :destroy]
  resources :repositories, except: [:edit] do
    resources :notes
  end


  root "welcome#index"

  get '/test', :to => 'repositories#test'

  get '/search', :to => 'searches#index'

  get '/code-review', :to => 'code_reviews#new_code_review'

  get '/branch', :to => 'repositories#change_branch'

  # Github Callback
  get '/auth/github/callback', to: 'sessions#create'
  # Logout
  get '/sessions/destroy', to: 'sessions#destroy', as: :logout

end

app/views/shared/_all_saved_repositories.html.erb
<div class="all-saved-repositories">
  <h4>Saved Repositories</h4>

  <% Repository.all.each do |repository| %>
    <a href='/repositories/<%=repository.id%>'><%=repository.name%></a>
    <br><br>
  <% end %>

</div>

app/views/shared/_dashboard.html.erb
<section class="row">
	<section class="col-md-3"></section>
	<h3 class="col-md-6 page_titles">Dashboard</h3>
	<section class="col-md-3"></section>
</section>
<section class="row">
	<section class="col-md-3"></section>
	<p class="col-md-6 page_titles">(This is the logged in users dashboard)</p>
	<section class="col-md-3"></section>
</section>
<% unless @repositories.nil? %>
<% @repositories.each do |repository| %>
	<section class="row">
		<section class="col-md-5"></section>
		<a href="/code-review?username=<%=repository['repo_owner']%>&repo=<%=repository['name']%>" class="col-md-2 page_titles"><%= repository.name %></a>
		<section class="col-md-5"></section>
	</section>
<% end %>
<% end %>

app/views/shared/_note_box.html.erb
<div class="note-box">

<%= form_for :note, :html => {id: "note-form"}, url: repository_notes_path(repository_id: @repository.id), method: :post, locals: {repository: @repository, username: @username} do |f| %>

  <div class="form-group">
    <%= f.label :content, "Notes", :class => "text_area_label" %>
    <%= f.text_area :content, :class => "form-control" %>
  </div>

  <%= f.hidden_field :username, value: "#{@username}" %>

  <%= f.hidden_field :repository_name, value: "#{@repository.name}" %>

  <%= f.hidden_field :reviewer_id, value: "#{session[:user_id]}" %>

  <%= f.hidden_field :repository_id,
  value: "#{@repository.id}" %>

  <div class="form-group">
    <%= f.submit "Add Note", id: "submit-note", :class => "btn btn-default" %>
  </div>

<% end %>

</div>

<!-- <div class="note-box">

  <form role="form" action="/notes" method="post">

    <div class="form-group">
      <label class="notes_label" for="content">Notes</label>
    </div>

    <div class="form-group notes_textarea_div">
      <textarea class="form-control" name="content"></textarea>
    </div>

    <input type="hidden" name="username" value="#{@username}">
    <input type="hidden" name="repository_name" value="#{@repository}">
    <input type="hidden" name="reviewer_id" value="wow">

    <div class="form-group">
      <input class="form-control notes_button" type="submit" value="Add">
    </div>

  </form>

</div> -->

app/views/shared/_notes.html.erb
<div class="notes">
  <!--   Success! Made this display notes for this particular repo -->
   <% if Note.where(repo_uid: @repository.repo_uid) %>
      <% Note.where(repo_uid: @repository.repo_uid).each do |note| %>
        <%= note.content %><br><br>
      <% end %>
  <% end %>
</div>